# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.IntegerField(default=0)),
                ('group_assigned', models.IntegerField(default=0)),
                ('patient_summary', models.TextField(default='')),
                ('occurrence_date', models.DateField()),
                ('pressor_events_day_summary', models.TextField()),
                ('bp_trend_day_summary', models.TextField()),
                ('culture_all_summary', models.TextField()),
                ('abx_day_summary', models.TextField()),
                ('abx_all_summary', models.TextField()),
                ('lactate_all_summary', models.TextField()),
                ('measurement_day_summary', models.TextField()),
                ('dc_note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(default=0)),
                ('subject_id', models.IntegerField(default=0)),
                ('occurence_date', models.DateField()),
                ('answer_responder1', models.IntegerField(default=None)),
                ('answer_responder2', models.IntegerField(default=None)),
                ('answer_responder3', models.IntegerField(default=None)),
                ('answer_responder4', models.IntegerField(default=None)),
                ('note_responder1', models.CharField(max_length=255)),
                ('note_responder2', models.CharField(max_length=255)),
                ('note_responder3', models.CharField(max_length=255)),
                ('note_responder4', models.CharField(max_length=255)),
                ('marking1', models.IntegerField()),
                ('marking2', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qshock.CaseQuestion')),
            ],
        ),
    ]
